
version: '3.3'
services:  
  ###########################################################
  ###################     DATABASE    #######################
  ###########################################################
  db:
    image: postgres:9.4
    restart: always
    environment: 
        - POSTGRES_USER=alp
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=alpdb
    volumes:
      - db_data:/var/lib/postgresql/data
    # optional port
    ports: ["5432:5432"]

  redis:
    image: redis
    hostname: redis
    ports:
     - "6379:6379"

volumes:
  db_data:
  