security:
  oauth2:
    resource:
      id: resource_id
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/alpdb
    username: alp
    password: postgres
    # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    generate-ddl: true
  redis:
    host: localhost
    port: 6379
    database: 0
    pool:
      max-active: 8
      max-idle: 8
      max-wait: 0
      min-idle: 0
    timeout: 5000
logging:
  level:
    idv.hsiehpinghan: INFO
    root: INFO